version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: stealth_game_backend
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: stealth_game_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
